# NUMPY REFRESHER

<img src="figures/numpy.jpg" width="40%">

Fundamental for linear algebra calulations in Python:
* N-dimensional arrays with fancy indexing
* fast implementation, sophisticated libraries for linear algebra
* tools for glueing C/C++ and Fortran
* more: www.numpy.org

In [3]:
import numpy as np

# generate a rand matrix

# Generating a random array
X = np.random.random((2, 2))

#print some matrix stuff, you can play with tab completion to check for possible operations
print X 
print X[1] #row
print X [:,1] #column
print X.T #transpose

[[ 0.29495178  0.41196616]
 [ 0.19281704  0.92199855]]
[ 0.19281704  0.92199855]
[ 0.41196616  0.92199855]
[[ 0.29495178  0.19281704]
 [ 0.41196616  0.92199855]]


In [4]:
# Turning a row vector into a column vector
y = np.linspace(0, 12, 5)
print(y)

[  0.   3.   6.   9.  12.]


In [5]:
# indexing by an array of integers (fancy indexing)
indices = np.array([3, 1, 0])
print(indices)
X[:, indices]

[3 1 0]


IndexError: index 3 is out of bounds for axis 1 with size 2

# SCIPY & MATPLOTLIB REFRESHER

<img src="figures/scipy_logo.png" width="40%">

Fundamental for scientific computing in Python:
* ecosystem for computational math
* integrates also tools for data analysis, plotting etc.
* more: www.scipy.org

In [ ]:
from scipy import sparse

# Create a random array with a lot of zeros
X = np.random.random((10, 5))
print(X)

In [ ]:
# turn X into a csr (Compressed-Sparse-Row) matrix
X_csr = sparse.csr_matrix(X)
print(X_csr)

In [ ]:
# there are also handy magic commands
%matplotlib inline

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# plotting a line
x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))

In [ ]:
# scatter-plot points
x = np.random.normal(size=500)
y = np.random.normal(size=500)
plt.scatter(x, y)

In [ ]:
# showing images
x = np.linspace(1, 12, 100)
y = x[:, np.newaxis]

im = y * np.sin(x) * np.cos(y)
print(im.shape)

In [ ]:
# imshow - note that origin is at the top-left by default!
plt.imshow(im)

In [ ]:
# Contour plot - note that origin here is at the bottom-left by default!
plt.contour(im)

In [ ]:
# 3D plotting
from mpl_toolkits.mplot3d import Axes3D
ax = plt.axes(projection='3d')
xgrid, ygrid = np.meshgrid(x, y.ravel())
ax.plot_surface(xgrid, ygrid, im, cmap=plt.cm.jet, cstride=2, rstride=2, linewidth=0)